name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Sentiment-Analysis
            git pull origin main
            pip3 install -r requirements.txt --no-cache-dir
            pkill -f streamlit || true
            nohup streamlit run app.py --server.port 8501 --server.headless true > ~/streamlit.log 2>&1 &